name: multi_lang_month_converter
description: A Dart package to convert month numbers to names in Uzbek, Russian, and English.
version: 1.0.0

homepage: https://github.com/AkmaljonAbdirakhimov/multi_lang_month_converter
repository: https://github.com/AkmaljonAbdirakhimov/multi_lang_month_converter

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

license: MIT
